import type { Author, Post } from "./types";

export const ME: Author = {
  id: "u-me",
  name: "Ananya Sharma",
  location: "Tilonia, Rajasthan",
  bio: "I write the house stories. Village to village.",
  initials: "AS",
};

const people: Author[] = [
  ME,
  { id: "u2", name: "Harish Gurjar", location: "Tilonia, Rajasthan", bio: "", initials: "HG" },
  { id: "u3", name: "Sita Devi", location: "Raghurajpur, Odisha", bio: "", initials: "SD" },
  { id: "u4", name: "Moa Angami", location: "Khonoma, Nagaland", bio: "", initials: "MA" },
  { id: "u5", name: "Meera Nair", location: "Kumbalangi, Kerala", bio: "", initials: "MN" },
  { id: "u6", name: "Kamal Ben", location: "Hodka, Gujarat", bio: "", initials: "KB" },
  { id: "u7", name: "Bhaben Das", location: "Kamalabari, Assam", bio: "", initials: "BD" },
  { id: "u8", name: "Pallavi Reddy", location: "Pochampally, Telangana", bio: "", initials: "PR" },
];

function ago(hours: number) {
  return new Date(Date.now() - hours * 3600 * 1000).toISOString();
}

export const SEED_POSTS: Post[] = [
  {
    id: "p01",
    title: "Tilonia still keeps this rite the morning after Holi",
    body: "The day after colour, the women gather in the courtyard. No powder. Songs. Grandmother used to say — earth first, then voice. I did the same this year.",
    imageUrl: "/places/holi.jpg",
    audioUrl: "/seed/m01.wav",
    category: "parampara",
    communitySlug: "tilonia",
    author: people[1],
    createdAt: ago(2),
    likes: 128,
    fromVoice: true,
    comments: [
      {
        id: "c1",
        author: people[7],
        body: "We do this too. The songs are a little different.",
        createdAt: ago(1),
        replies: [{ id: "r1", author: people[1], body: "Send a clip next time. We’ll match them.", createdAt: ago(0.5) }],
      },
    ],
  },
  {
    id: "p02",
    title: "Namghar before dawn in Kamalabari",
    body: "On Majuli the river eats the bank and the satra moves. Babuji still sits on the same stool for tea. The mask workshop opens after prayer.",
    imageUrl: "/places/varanasi.jpg",
    audioUrl: "/seed/m02.wav",
    category: "kahani",
    communitySlug: "kamalabari",
    author: people[6],
    createdAt: ago(5),
    likes: 241,
    fromVoice: true,
    comments: [{ id: "c2", author: ME, body: "Which satra? I’ll look for it next winter.", createdAt: ago(4), replies: [] }],
  },
  {
    id: "p03",
    title: "When the embroidery needle hangs on the wall in Hodka",
    body: "Mother says mirror-work cannot be rushed. Cloth in the sun, thread at night. Tourists take pictures of the bhunga. We count — how many mirrors, how many breaths.",
    imageUrl: "/places/kutch.jpg",
    audioUrl: "/seed/m03.wav",
    category: "hastashilp",
    communitySlug: "hodka",
    author: people[5],
    createdAt: ago(9),
    likes: 96,
    fromVoice: true,
    comments: [],
  },
  {
    id: "p04",
    title: "Banana leaf meals are not only for festivals",
    body: "In Kumbalangi, Monday rice still arrives on a leaf. Amma says washing plates is worse than leaving the leaf for the cow. The backwater never unlearned that.",
    imageUrl: "/places/kochi.jpg",
    category: "khanpan",
    communitySlug: "kumbalangi",
    author: people[4],
    createdAt: ago(14),
    likes: 73,
    fromVoice: false,
    comments: [],
  },
  {
    id: "p05",
    title: "Jagannath’s eyes go on last",
    body: "Tamarind glue first, then two layers of cloth. Colour from stone. The pattachitra wakes when the eyes go on — that’s what Baba taught. This is housework, not tourism.",
    imageUrl: "/places/raghurajpur.jpg",
    audioUrl: "/seed/m05.wav",
    category: "lokkala",
    communitySlug: "raghurajpur",
    author: people[2],
    createdAt: ago(20),
    likes: 188,
    fromVoice: true,
    comments: [{ id: "c3", author: people[3], body: "The hand doesn’t fit in a camera. Keep the voice.", createdAt: ago(18), replies: [] }],
  },
  {
    id: "p06",
    title: "Terraces in Khonoma before the mist lifts",
    body: "The village decided the forest comes first. Morning is alder, not the highway. Grandfather still walks the terrace wall.",
    imageUrl: "/places/khonoma.jpg",
    audioUrl: "/seed/m06.wav",
    category: "sthaan",
    communitySlug: "khonoma",
    author: people[3],
    createdAt: ago(28),
    likes: 54,
    fromVoice: true,
    comments: [],
  },
  {
    id: "p07",
    title: "The lane in Chandelao where the wall still breathes",
    body: "A haveli wall holds horses and ships together. Not a museum. The neighbour keeps the key. Ask, and he opens it.",
    imageUrl: "/places/udaipur.jpg",
    category: "sthaan",
    communitySlug: "chandelao",
    author: people[1],
    createdAt: ago(36),
    likes: 112,
    fromVoice: false,
    comments: [],
  },
  {
    id: "p08",
    title: "Holi at home, Tilonia",
    body: "After Holi we keep jaggery-water in the courtyard. It isn’t in the books. It’s grandmother’s ledger. The radio still plays the village news.",
    imageUrl: "/places/holi.jpg",
    audioUrl: "/seed/m08.wav",
    category: "tyohar",
    communitySlug: "tilonia",
    author: ME,
    createdAt: ago(48),
    likes: 67,
    fromVoice: true,
    comments: [],
  },
  {
    id: "p09",
    title: "The count of ikat in Pochampally",
    body: "A weaver said: tie the colour, then the cloth will speak. I only listened. Then I wrote it down.",
    imageUrl: "/places/pochampally.jpg",
    category: "hastashilp",
    communitySlug: "pochampally",
    author: people[7],
    createdAt: ago(60),
    likes: 45,
    fromVoice: false,
    comments: [],
  },
  {
    id: "p10",
    title: "Bamboo and paddy-fish in Hong village",
    body: "In Ziro the field holds rice and fish together. Children watch phones. The old still watch the terrace water.",
    imageUrl: "/places/bhopal.jpg",
    audioUrl: "/seed/m10.wav",
    category: "lokkatha",
    communitySlug: "hong",
    author: people[3],
    createdAt: ago(72),
    likes: 81,
    fromVoice: true,
    comments: [],
  },
];

export const TRENDING = [
  "Pattachitra from Raghurajpur",
  "Holi in Tilonia",
  "Bhunga embroidery, Hodka",
  "Green village, Khonoma",
];
